name: Excavator

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */8 * * *"

jobs:
  excavate:
    name: Excavate
    runs-on: windows-latest
    # if: ${{ always() }}
    # needs: checkver
    steps:
      - uses: actions/checkout@v3
      - name: Git config
        run: |
          git config --local user.email "78083448+JaimeZeng@users.noreply.github.com"
          git config --local user.name "JaimeZeng"
      - name: Excavate
        uses: ScoopInstaller/GithubActions@main
        env:
          USER_EMAIL: 78083448+JaimeZeng@users.noreply.github.com
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          SKIP_UPDATED: "1"
