name: Sync

on:
  schedule:
    - cron: "0 11,23 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Sync
        run: |
          set -euxo pipefail
          git config --local user.email "78083448+JaimeZeng@users.noreply.github.com"
          git config --local user.name "JaimeZeng"
          git clone --depth=1 https://github.com/Ash258/Scoop-JetBrains.git
          git clone --depth=1 https://github.com/v2rayA/v2raya-scoop.git

          cd Scoop-JetBrains/bucket
          ls | grep -E "RC|EAP" | grep -v "Toolbox" | xargs -t -i rm -f {}
          cd ../../

          cp -f v2raya-scoop/bucket/*.json bucket/
          cp -f Scoop-JetBrains/bucket/*.json bucket/
          cp -f Scoop-JetBrains/scripts/* scripts/

          rm -rf v2raya-scoop/ Scoop-JetBrains/
      - name: Commit
        run: |
          git add .
          git commit -m "Sync Bucket"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
