name: TOC_Sync
on:
  push:
    branches: [master]
    paths:
      - "bucket/*.json"
      - "!README.md"
  workflow_dispatch:
  # workflow_run:
  #   workflows: ["Excavator"]
  #   types: [completed]
  #   branches: [master]
  # schedule:
  #   - cron: "30 * * * *"
jobs:
  toc:
    name: TOC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Update package manager database
        run: sudo apt-get update
      - name: Install Dependence
        run: sudo apt-get install curl jq
      - name: Git config
        run: |
          git config --local user.email "78083448+JaimeZeng@users.noreply.github.com"
          git config --local user.name "JaimeZeng"
      - name: Generate TOC
        run: sed -i 's/\r$//' toc.sh && bash toc.sh
      - name: Commit
        run: |
          git add .
          git commit -m "update README.md"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}

      - name: Import ssh private key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" | sed 's/\\n/\n/g' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Git config
        run: |
          git config --local user.email "78083448+JaimeZeng@users.noreply.github.com"
          git config --local user.name "JaimeZeng"
      - name: Replace manifest
        run: |
          cd bucket/
          find . -name '*.json' -printf "'%f'\n" | xargs -i sed -i 's|\(https://github.com/.*/releases/download\)|https://github.do/\1|g;s|\(https://raw.githubusercontent.com/\)|https://github.do/\1|g' {}
      - name: Commit changes
        run: |
          git add .
          git commit -m "Sync"
      - name: Sync
        run: |
          git config --local core.sshCommand "/usr/bin/ssh -i ~/.ssh/id_rsa"
          # https://stackoverflow.com/questions/13363553/git-error-host-key-verification-failed-when-connecting-to-remote-repository/13364116#13364116
          # ssh-keygen -R e.coding.net
          ssh-keyscan -t rsa e.coding.net >> ~/.ssh/known_hosts
          git remote add coding git@e.coding.net:ryanjie/scoop/scoop-apps.git
          git push -u coding master -f
      - name: Remove ssh private key
        run: rm -f ~/.ssh/id_rsa
